# Generated by Django 5.1.7 on 2025-03-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('primary', 'Primary (Front)'), ('secondary', 'Secondary (Back)'), ('additional', 'Additional')], default='additional', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('image_type__in', ['primary', 'secondary'])), fields=('product', 'image_type'), name='unique_image_type_per_product'),
        ),
    ]
