# Generated by Django 5.1.7 on 2025-03-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_policy',
            field=models.CharField(choices=[('single', 'No Sizes (Single Product)'), ('multiple', 'Multiple Sizes Available')], default='single', help_text='Determine if this product comes in multiple sizes or is a single product.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Stock quantity for single-size products.'),
        ),
    ]
