# Generated by Django 5.1.7 on 2025-04-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_size_policy_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
